//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Butterfly.Service.Schedule
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleEntry
    {
        public string ParamId { get; set; }
        public int Hour { get; set; }
        public int Minute { get; set; }
        public int RecId { get; set; }
        public int Time { get; set; }
    }
}
